server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/month?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  application:
    name: provider-server # 应用名称
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true  #格式化sql
mybatis:
  mapper-locations: classpath*:mapper/*.xml
logging:
  level:
    com.shiqihang.server: debug  #sql日志打印